# ----------------------------------------------------------------------------------
[profile.upgrades] # Required for Upgrades Plugin
# ----------------------------------------------------------------------------------
build_info = true
ast = true
ffi = false
extra_output = ["storageLayout"] # Foundry Plugins
# ----------------------------------------------------------------------------------
[profile.default] # Project Configs
# ----------------------------------------------------------------------------------
# Contract sources
src = 'src'
# The test directory
test = 'test'
# The script directory
script = 'script'
# The artifact directory
out = 'out'
# A list of paths to look for libraries in
libs = ["dependencies"]
# Whether to cache builds or not
cache = true
# The cache directory if enabled
cache_path = 'cache'
# Where the broadcast logs are stored
broadcast = 'broadcast'
# Whether to ignore the cache
force = false
# Disable linting
lint_on_build = false
# ----------------------------------------------------------------------------------
# Solidity Compiler
# ----------------------------------------------------------------------------------
# re-mappings
remappings = [
]
# Whether to autodetect remappings by scanning the `libs` folders recursively
auto_detect_remappings = true
# additional solc include paths
include_paths = []
# allow paths
allow_paths = []
# A list of deployed libraries to link against
libraries = []
# Compiler Version
# solc-version = "0.8.30"
# auto-detect the solc version
auto_detect_solc = true
# Disables downloading missing solc versions
offline = false
# Ignore warnings from a file
ignored_warnings_from = []
# [ license: 1878, code-size: 5574, func-mutability: 2018,  unused-var: 2072, unused-param: 5667,  unused-return: 9302,  virtual-interfaces: 5815, missing-receive-ether: 3628, shadowing: 2519,  same-varname: 8760  unnamed-return: 6321,  unreachable: 5740, pragma-solidity: 3420, constructor-visibility 2462, initcodesize 3860, transient-storage: 2394, too-many warnings: 4591, Function state mutability can be restricted to pure 2018,]
ignored_error_codes = [1878, 5574, 2018, 2072]
# Treat compiler warnings as errors
deny_warnings = false
# homestead, tangerineWhistle, spuriousDragon, byzantium, constantinople, petersburg, istanbul, berlin, london, paris, shanghai, cancun, prague(default)
evm_version = 'prague'
# defult, strip, debug, verboseDebug
revert_strings = "default"
# evm.assembly, ewasm, ir, ir-optimized, metadata.
extra_output_files = []
# "abi" , "evm.bytcode", "evm.deployedBytecode", "evm.methodIdentifiers"
extra_output = []
# "none", "bzzr1", "ipfs
bytecode_hash = "none"
#, Instructs solidity compiler to generate bytecode only for required contracts. Reduce compile time for `forge test`, Experimental.
sparse_mode = false
# Enables or disables the optimizer
optimizer = true
# The number of optimizer runs
optimizer_runs = 200
# Whether to use the Yul optimizer
via_ir = true
# Compilation to use literal content and not URLs
use_literal_content = false
# [profile.default.optimizer_details]
# The peephole optimizer is always on if no details/optimizer=false are given, use details to switch it off.
# peephole = true
# inliner = false
# jumpdestRemover = true
# orderDependent = true
# deduplicate = false
# cse = false
# constantOptimizer = false
# yul = false
# [profile.default.optimizer_details.yulDetails]
# stackAllocation = true
# optimizerSteps = 'dhfoDgvulfnTUtnIf'
# optimizerSteps = 'dhfoD[xarrscLMcCTU]uljmul:fDnTOcmu'
# optimzerSteps = 'dhfoDgvulfnTUtnIf [ xa[r]EscLM cCTUtTOntnfDIul Lcul Vcul [j] Tpeul xa[rul] xa[r]cL gvif CTUca[r]LSsTFOtfDnca[r]Iulc ] jmul[jul] VcTOcul jmul : fDnTOcmu'
# Use the given hash method for the metadata hash that is appended to the bytecode.
cbor_metadata = false
# Test preprocessor enables fast compilation times
# dynamic_test_linking = true
# ----------------------------------------------------------------------------------
# Compilation Restrictions
# ----------------------------------------------------------------------------------
# add via_ir profile
# additional_compiler_profiles = [ { name = "via-ir", via_ir = true } ]

# enforce compiling tests without via_ir and only some heavy contract with via_ir
# note: it will only work if tests are using vm.deployCode to deploy contract
# compilation_restrictions = [
    # { paths = "test/**", via_ir = false },
    # { paths = "src/Counter.sol", via_ir = true },
# ]
# ----------------------------------------------------------------------------------
[profile.defalut.model_checker] # Model checker settings.
# ----------------------------------------------------------------------------------
# contracts = {}
# Sets how division and modulo operations should be encoded
# div_mod_with_slacks
# engine = 'chc' / 'bmc' 'all'
# engine = 'none'
# invariant = 'contract' / 'reentrancy'
# show_unproved = false / true
# solvers = cvc4 / eld (introduced in v0.8.18) / smtlib2 / z3
# timeout = 10000
# 'default'/ 'assert' / undeflow / overflow / divByZero / constantCondition / popEmptyArray / outOfBounds / default
# targets = 'default'
# ----------------------------------------------------------------------------------
# Testing
# ----------------------------------------------------------------------------------
# Configures the permissions of cheat codes that touch the file system
[[profile.default.fs_permissions]]
access = "read-write"
path = "./"
# The verbosity of tests
verbosity = 1
# Whether or not to enable `vm.ffi`
ffi = false
# The address of `msg.sender` in tests
sender = "0xb4c79daB8f259C7Aee6E5b2Aa729821864227e84"
# The address of `tx.origin` in tests
tx_origin = "0xb4c79daB8f259C7Aee6E5b2Aa729821864227e84"
# The initial balance of the test contract
initial_balance = '0xffffffffffffffffffffffff'
# The `block.number` value during EVM execution
block_number = 1
# The chain ID we are on in tests
chain_id = 31337
# The gas limit in tests
gas_limit = 9223372036854775807
# The gas price in tests (in wei)
gas_price = 0
# The block basefee in tests (in wei)
block_base_fee_per_gas = 0
# The address of `block.coinbase` in tests
block_coinbase = '0x0000000000000000000000000000000000000000'
# The block timestamp in tests
block_timestamp = 1
# The block difficulty in tests
block_difficulty = 0
# A list of contracts to output gas reports for
gas_reports = ['*']
no_storage_caching = false
# A list of contracts to ignore for gas reports
gas_reports_ignore = []
no_rpc_rate_limit = false
# caching
[profile.default.rpc_storage_caching]
chains = 'all'
endpoints = 'all'
# rpc call
# eth_rpc_url = ""
# etherscan_api_key = ""
# Only runs test methods  matching the test
# match-test= 'regex'
# Only runs test methods not matching the test
# no-match-test= 'regex'
# Only runs test methods not matching the test
# no-match-test= 'regex'
# Only runs test methods on files  matching the contract
# match-contract = 'regex'
# Only runs test methods on files not matching the contract
# no-match-contract = 'regex'
# Only runs test methods on files  matching the path
# match-path = 'regex'
# Only runs test methods on files not matching the path
# no-match-path = 'regex'
# threads number of cores default
# threads = 4
# show progress
# show_progress = true
# The block gas limit
# block_gas_limit = None
# The memory limit of the EVM (32 MB by default)
memory_limit = 33554432
# Print the names of the compiled contracts
names = false
# Print the sizes of the compiled contracts
sizes = false
# Contains alias -> URL|Env pairs for RPC endpoints that can be accessed during testing
[rpc_endpoints]
mainnet="https://rpc.flashbots.net/fast"
scroll="https://rpc.scroll.io"
linea="https://1rpc.io/linea"
polygon="wss://polygon-bor-rpc.publicnode.com"
blast="https://blast.drpc.org"
optimism="https://mainnet.optimism.io"
arbitrum="wss://arbitrum-one-rpc.publicnode.com"
bsc="https://bsc-dataseed.binance.org/"
base="https://base.llamarpc.com"
moonriver="https://rpc.api.moonbeam.network"
avalanche="https://endpoints.omniatech.io/v1/avax/mainnet/public"
fantom="https://rpc.ankr.com/fantom"
gnosis="https://rpc.ankr.com/gnosis"
celo="https://rpc.ankr.com/celo"
odyssey="https://odyssey.ithaca.xyz"
sepolia="https://rpc-sepolia.flashbots.net/"
# The number of seconds to wait before vm.prompt reverts with a timeout.
# prompt_timeout=120
# ----------------------------------------------------------------------------------
[fuzz]
# ----------------------------------------------------------------------------------
# The number of fuzz runs for fuzz tests
runs = 1000
# The maximum number of test case rejections allowed
max_test_rejects = 65536
# Optional seed for the random number generator
# seed = 0
# A higher dictionary weight biases fuzz inputs towards "interesting" values, e.g. boundary values like type(uint256).max
dictionary_weight = 40
# The flag indicating whether to include values from storage
include_storage = true
# The flag indicating whether to include push bytes values
include_push_bytes = true
# Number of runs to use for generating gas report.
gas_report_samples = 256
# Path where fuzz failures are recorded and replayed.
failure_persist_dir = "./cache/fuzz"
# Name of the file to record fuzz failures.
failure_persist_file = "failures"
# Display logs
show_logs = false
# ----------------------------------------------------------------------------------
[invariant]
# ----------------------------------------------------------------------------------
# Duration to run test Timeout in seconds
timeout = 120
# The number of runs that must execute for each invariant test group
runs = 256
# The number of calls executed to attempt to break invariants in one run
depth = 500
# Fails the invariant fuzzing if a revert occurs
fail_on_revert = false
# Allows overriding an unsafe external call when running invariant tests. eg. reentrancy checks
call_override = false
# The weight of the dictionary
dictionary_weight = 80
# The flag indicating whether to include values from storage
include_storage = true
# The flag indicating whether to include push bytes values
include_push_bytes = true
# The maximum number of attempts to shrink a failed the sequence.
shrink_run_limit = 5000
# The maximum number of rejects via vm.assume which can be encountered during a single invariant run
max_assume_rejects = 65536
# Number of runs to use for generating gas report.
gas_report_samples = 256
# Path where invariant failures are recorded and replayed.
failure_persist_dir = "./cache/invariant"
# whether to collect and display fuzzed selectors metrics in test report.
show_metric=true
# ----------------------------------------------------------------------------------
[fmt]
# ----------------------------------------------------------------------------------
# "single","multi", "preserve"
single_line_statement_blocks = "multi"
# params_first_multi, params_first, attribute_first, all
multiline_func_header = 'params_first_multi'
sort_imports = true
contract_new_lines = true
override_spacing = false
line_length = 90
tab_width = 4
# Print spaces between brackets
bracket_spacing = false
# "long","short", "preserve"
int_types = "long"
# Style of quotation marks
quote_style = "double"
# Style of underscores in number literals
number_underscore = "thousands"
# preserve, remove, bytes
hex_underscore= "remove"
wrap_comments = true
ignore = ["src/console.sol", "src/console2.sol"]
# ----------------------------------------------------------------------------------
[doc]
# ----------------------------------------------------------------------------------
# Default output directory for documentation
out = 'doc'
# Title for the documentation
title = 'Forge Documentation'
# The path to use provide book.toml. It will be merged during doc gen
book = 'book.toml'
# The git repository URL to used to provide links to git source files.
repository = ""
# List of files to ignore while generation documentation
ignore = []
# ----------------------------------------------------------------------------------
[etherscan]
# ----------------------------------------------------------------------------------
mainnet = { key = "${ETHERSCAN_API_KEY}", chain = "mainnet" }
optimism = { key = "${ETHERSCAN_API_KEY}", chain = "optimism" }
fantom = { key = "${ETHERSCAN_API_KEY}", chain = "fantom" }
arbitrum = { key = "${ETHERSCAN_API_KEY}", chain = "arbitrum" }
bsc = { key = "${ETHERSCAN_API_KEY}", chain = "bsc", url = "https://api.bscscan.com/" }
moonriver = { key = "${ETHERSCAN_API_KEY}", chain = "moonriver" }
base = { key = "${ETHERSCAN_API_KEY}", chain = "base" }
gnosis = { key = "${ETHERSCAN_API_KEY}", chain = "gnosis" }
avalanche = { key = "${ETHERSCAN_API_KEY}", chain = "avalanche" }
# polygon = { key = "${ETHERSCAN_API_KEY}", chain = "polygon" }
celo = { key = "${ETHERSCAN_API_KEY}", chain = "celo" }
unknown_chain = { key = "ABCDEFG", url = "<etherscan api url for this chain>" }
# ----------------------------------------------------------------------------------
[soldeer]
# ----------------------------------------------------------------------------------
# whether soldeer manages remappings
remappings_generate = false
# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false
# whether to suffix the remapping with the version: `name-a.b.c`
remappings_version = false
# a prefix to add to the remappings ("@" would give `@name`)
remappings_prefix = ""
# where to store the remappings ("txt" for `remappings.txt` or "config" for `foundry.toml`)
# ignored when `soldeer.toml` is used as config (uses `remappings.txt`)
remappings_location = "txt"
# Automatically install sub dependencies when running tests
# recursive_deps = true
# ----------------------------------------------------------------------------------
[dependencies]
# ----------------------------------------------------------------------------------
forge-std = "1.9.7"
murky = "0.1.0"
"@openzeppelin-contracts-upgradeable" = "5.3.0"
openzeppelin-foundry-upgrades = "0.4.0"
"@openzeppelin-contracts" = "5.3.0"
# ----------------------------------------------------------------------------------
[profile.lint]
# ----------------------------------------------------------------------------------
severity=["High","Med"]
exclude_lints = ["mixed-case-functions"]
ignore = []
lint_on_build=false
# ----------------------------------------------------------------------------------
